export interface ChatCustomization {
  selectedThemeName: string;
  styleOverrides?: Partial<ChatTheme>;
  initialMessage?: string;
}

export interface ChatTheme {
  name: string;
  iconColor: string;
  iconBg: string;
  iconBorderColor: string;
  headerFooterColor: string;
  chatBg: string;
  sentBubbleColor: string;
  receivedBubbleColor: string;
  sentTextColor: string;
  receivedTextColor: string;
  textInputColor: string;
  sendButtonColor: string;
  borderRadius: string; // Can be tailwind values or pixel values like '1rem'
}

export const CHAT_THEME_DISPLAY_NAMES: Record<keyof ChatTheme, string> = {
  name: 'Name',
  iconColor: 'Icon Color',
  iconBg: 'Icon Background Color',
  iconBorderColor: 'Icon Border Color',
  headerFooterColor: 'Header/Footer Color',
  chatBg: 'Chat Background Color',
  sentBubbleColor: 'Sent Bubble Color',
  receivedBubbleColor: 'Received Bubble Color',
  sentTextColor: 'Sent Text Color',
  receivedTextColor: 'Received Text Color',
  textInputColor: 'Text Input Color',
  sendButtonColor: 'Send Button Color',
  borderRadius: 'Border Radius',
};

export const CHAT_THEMES: ChatTheme[] = [
  {
    name: 'Default',
    iconColor: '#3b82f6',
    iconBg: '#ffffff',
    iconBorderColor: '#cbd5e1',
    headerFooterColor: '#f8fafc',
    chatBg: '#ffffff',
    sentBubbleColor: '#3b82f6',
    receivedBubbleColor: 'rgb(207, 226, 255)',
    sentTextColor: '#000000',
    receivedTextColor: '#000000',
    textInputColor: '#ffffff',
    sendButtonColor: '#3b82f6',
    borderRadius: '16px',
  },
  {
    name: 'Midnight',
    iconColor: '#60a5fa',
    iconBg: '#1e293b',
    iconBorderColor: '#334155',
    headerFooterColor: '#0f172a',
    chatBg: '#1e293b',
    sentBubbleColor: '#3b82f6',
    receivedBubbleColor: '#334155',
    sentTextColor: '#ffffff',
    receivedTextColor: '#e2e8f0',
    textInputColor: '#334155',
    sendButtonColor: '#3b82f6',
    borderRadius: '16px',
  },
  {
    name: 'Skyline',
    iconColor: '#3b82f6',
    iconBg: '#ffffff',
    iconBorderColor: '#cbd5e1',
    headerFooterColor: '#e0f2fe',
    chatBg: '#f0f9ff',
    sentBubbleColor: '#3b82f6',
    receivedBubbleColor: '#e0f2fe',
    sentTextColor: '#ffffff',
    receivedTextColor: '#000000',
    textInputColor: '#ffffff',
    sendButtonColor: '#3b82f6',
    borderRadius: '1.5rem',
  },
  {
    name: 'Plum',
    iconColor: '#8b5cf6',
    iconBg: '#f3e8ff',
    iconBorderColor: '#ddd6fe',
    headerFooterColor: '#faf5ff',
    chatBg: '#f8f0fc',
    sentBubbleColor: '#8b5cf6',
    receivedBubbleColor: '#e9d5ff',
    sentTextColor: '#ffffff',
    receivedTextColor: '#1f2937',
    textInputColor: '#000000',
    sendButtonColor: '#8b5cf6',
    borderRadius: '1.5rem',
  },
  {
    name: 'Neon Plum',
    iconColor: '#c084fc',
    iconBg: '#1e1b2e',
    iconBorderColor: '#4b4453',
    headerFooterColor: '#2a263a',
    chatBg: '#1e1b2e',
    sentBubbleColor: '#8b5cf6',
    receivedBubbleColor: '#3b3054',
    sentTextColor: '#ffffff',
    receivedTextColor: '#d1d5db',
    textInputColor: '#2a263a',
    sendButtonColor: '#a855f7',
    borderRadius: '16px',
  },
  {
    name: 'Forest',
    iconColor: '#166534',
    iconBg: '#d1fae5',
    iconBorderColor: '#a7f3d0',
    headerFooterColor: '#ecfdf5',
    chatBg: '#ffffff',
    sentBubbleColor: '#10b981',
    receivedBubbleColor: '#d1fae5',
    sentTextColor: '#ffffff',
    receivedTextColor: '#000000',
    textInputColor: '#ffffff',
    sendButtonColor: '#10b981',
    borderRadius: '1rem',
  },
  {
    name: 'Forest Night',
    iconColor: '#34d399',
    iconBg: '#0d1f1a',
    iconBorderColor: '#1f4034',
    headerFooterColor: '#142d26',
    chatBg: '#0f2e25',
    sentBubbleColor: '#10b981',
    receivedBubbleColor: '#1f4034',
    sentTextColor: '#ffffff',
    receivedTextColor: '#cbd5e1',
    textInputColor: '#142d26',
    sendButtonColor: '#10b981',
    borderRadius: '16px',
  },
  {
    name: 'Sunset',
    iconColor: '#ea580c',
    iconBg: '#fff7ed',
    iconBorderColor: '#fdba74',
    headerFooterColor: '#fff7ed',
    chatBg: '#fffaf0',
    sentBubbleColor: '#f97316',
    receivedBubbleColor: '#ffedd5',
    sentTextColor: '#ffffff',
    receivedTextColor: '#000000',
    textInputColor: '#ffffff',
    sendButtonColor: '#f97316',
    borderRadius: '1.25rem',
  },

  {
    name: 'Slate',
    iconColor: '#475569',
    iconBg: '#ffffff',
    iconBorderColor: '#cbd5e1',
    headerFooterColor: '#f1f5f9',
    chatBg: '#f8fafc',
    sentBubbleColor: '#64748b',
    receivedBubbleColor: '#e2e8f0',
    sentTextColor: '#ffffff',
    receivedTextColor: '#000000',
    textInputColor: '#ffffff',
    sendButtonColor: '#64748b',
    borderRadius: '0.5rem',
  },
  {
    name: 'Slate Edge',
    iconColor: '#94a3b8',
    iconBg: '#0f172a',
    iconBorderColor: '#1e293b',
    headerFooterColor: '#1e293b',
    chatBg: '#0f172a',
    sentBubbleColor: '#64748b',
    receivedBubbleColor: '#1e293b',
    sentTextColor: '#ffffff',
    receivedTextColor: '#e5e7eb',
    textInputColor: '#1e293b',
    sendButtonColor: '#64748b',
    borderRadius: '16px',
  },
  {
    name: 'Rose',
    iconColor: '#be123c',
    iconBg: '#fff1f2',
    iconBorderColor: '#fecdd9',
    headerFooterColor: '#fff1f2',
    chatBg: '#fffaf0',
    sentBubbleColor: '#ec4899',
    receivedBubbleColor: '#fee2e2',
    sentTextColor: '#ffffff',
    receivedTextColor: '#000000',
    textInputColor: '#ffffff',
    sendButtonColor: '#ec4899',
    borderRadius: '1.5rem',
  },
];
